### ISSUE TITLE
Make rendition configurable through css

### ISSUE THREAD

**Issue by getreu** [grego/cmark-syntax#2]
I like your crate and I am considering using it with [Tp-Note](https://github.com/getreu/tp-note).
What keeps me from doing is, that I there is no easy way to remove the underlines in your rendition.
I could disable them globally with CSS, but there should be a better way restricting the configuration to your code blocks.
Or, do I miss something?

**Comment by grego** [comment]
Currently, glyphs are put into `u` tags, which are underlined by default.
It could be disabled as
```css
code u {
  text-decoration: none;
}
```

I'm open to suggestions for a different tag to use, as I agree that underlines are not desired.

**Comment by getreu** [comment]
Thank you. I integrated `cmark-syntax` into the [Tp-Note's](https://blog.getreu.net/projects/tp-note/) latest [release 1.18.0](https://blog.getreu.net/projects/tp-note/#distribution)

**Comment by getreu** [comment]
I mentioned your crate in [Jens Getreu's blog - Tp-Note renders MathML and adds (some) syntax highlighting](https://blog.getreu.net/20221022-tp-note-news9/) (Release notes)
Thank you for your work. It is useful for note-taking.
