### ISSUE TITLE
Math should not be enclosed by  `

### ISSUE THREAD

**Issue by getreu** [grego/cmark-syntax#4]
The widely adopted syntax is without enclosing `:

[Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html#math)

> Anything between two `$` characters will be treated as TeX math. The opening `$` must have a non-space character immediately to its right, while the closing `$` must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, \$ 20,000 and \$30,000  won’t parse as math. If for some reason you need to enclose text in literal $ characters, backslash-escape them and they won’t be treated as math delimiters.

**Comment by grego** [comment]
Fixed in the [new release](https://github.com/grego/cmark-syntax/tree/v0.5.1). Text between `$` is now interpreted as math in inline mode, text between `$$` as math in display mode.
